import nextCoreWebVitals from 'eslint-config-next/core-web-vitals'
import nextTypescript from 'eslint-config-next/typescript'

/**
 * Linting was not running at all.
 *
 * This file loaded Next's two shareable configs through `FlatCompat`, which is
 * the adapter for the old .eslintrc format. eslint-config-next has shipped
 * native flat configs since v15, so the adapter was handed something that was
 * already flat, failed to validate it, and then crashed inside its own error
 * formatter trying to serialise the React plugin — which is circular. The
 * result was a stack trace about "Converting circular structure to JSON" that
 * says nothing about the actual cause, on every run, before a single file was
 * read. `npm run lint` had been exiting non-zero for that reason alone, which
 * also means the lint step of the CI workflow could never have passed.
 *
 * Imported directly, they are just arrays to spread.
 */
const eslintConfig = [
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    rules: {
      /**
       * Kept visible, not treated as a build failure.
       *
       * Every one of the six places this fires is the same deliberate thing:
       * set state once, on mount, from something only a browser knows — the
       * scroll position, a theme saved in localStorage, the currency the guest
       * chose last time, whether IntersectionObserver exists. None of it can be
       * read while rendering on the server, and rendering the browser's answer
       * during the first client render is a hydration mismatch, so it has to
       * happen in an effect. The rule is right that this pattern costs an extra
       * render and right that it is worth knowing about; it is not right that
       * it is a defect here.
       *
       * The genuinely better shape for most of them is useSyncExternalStore,
       * which would let the server render a declared snapshot instead. That is
       * a real refactor of working, tested components rather than a lint fix,
       * so it is left as one — and left as a warning so it stays on the list
       * rather than disappearing into an eslint-disable comment on each site.
       */
      'react-hooks/set-state-in-effect': 'warn',
      '@typescript-eslint/ban-ts-comment': 'warn',
      '@typescript-eslint/no-empty-object-type': 'warn',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          vars: 'all',
          args: 'after-used',
          ignoreRestSiblings: false,
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^(_|ignore)',
        },
      ],
    },
  },
  {
    // Generated by Payload on every schema change, and not ours to fix.
    ignores: ['.next/', 'src/payload-types.ts', 'src/payload-generated-schema.ts'],
  },
]

export default eslintConfig
